export const homeObjOne = {
  id: `about`,
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: `Invest in Art`,
  headline: `Art Art Art`,
  description: `To succesd in life is to know the value of your soul enchanted in canvas.`,
  buttonLabel: `Get in touch`,
  imgStart: true,
  img: require(`../../images/gallery2.jpg`),
  alt: "art",
  dark: true,
  primary: true,
  darkText: false,
};
